name: Test - Unit

on:
  pull_request:
    branches: [main]

env:
  PNPM_VERSION: 9.7.1
  NODE_VERSION: 20.x

jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Run Unit Tests
        run: pnpm test:unit
